version: '3.9'

services:
  tgbot:
    build: ./
    command: ./habrbot
    depends_on:
      - db
    environment:
      TOKEN: "свой токен"
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD: qwerty
      DBNAME: postgres
      SSLMODE: disable

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: qwerty